# Site settings
title: Morf
email: info@morf.design
description: > # this means to ignore newlines until "baseurl:"
  MORF is a design studio based in North Carolina. We build lasting brands, usable websites, and engaging environments for clients of all sizes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://morf.studio/" # the base hostname & protocol for your site
twitter_username: morfstudio
instagram_username: morfstudio
github_username:  morf-studio

collections: projects
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: kramdown

#Exclude files
exclude: [node_modules, gulpfile.js]
